# Generated by Django 5.2 on 2025-04-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harakisha', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='CylinderStatus',
        ),
    ]
