# Generated by Django 5.2 on 2025-04-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harakisha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cylinder',
            name='level_in_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
