# Generated by Django 5.2 on 2025-04-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harakisha', '0002_alter_cylinder_level_in_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cylinder',
            name='production_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
