# Generated by Django 5.2 on 2025-04-29 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harakisha', '0003_alter_cylinder_production_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cylinder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cylinders', to='harakisha.customer'),
        ),
    ]
